using System.Collections.Generic;

namespace BelSync
{
    public enum AppLanguage { English, Turkish, Arabic }

    public static class Lang
    {
        public static AppLanguage Current = AppLanguage.English;
        public static bool IsRtl => Current == AppLanguage.Arabic;

        public static string Get(string key)
        {
            switch (Current)
            {
                case AppLanguage.Turkish: return TR.ContainsKey(key) ? TR[key] : key;
                case AppLanguage.Arabic: return AR.ContainsKey(key) ? AR[key] : key;
                default: return EN.ContainsKey(key) ? EN[key] : key;
            }
        }

        private static readonly Dictionary<string, string> EN = new Dictionary<string, string>
        {
            { "title",           "BelSync" },
            { "schema",          "Schema" },
            { "table",           "Table" },
            { "keyCol",          "Key Column" },
            { "jsonData",        "JSON Data" },
            { "uploadFile",      "📂 Upload File" },
            { "pasteJson",       "📋 Paste JSON" },
            { "browse",          "Browse..." },
            { "preview",         "🔍 Preview" },
            { "sync",            "💾 Sync to DB" },
            { "rollback",        "↩ Rollback" },
            { "clear",           "🗑 Clear" },
            { "settings",        "⚙ Settings" },
            { "theme",           "🌙 Dark Mode" },
            { "themeLight",      "☀ Light Mode" },
            { "total",           "Total" },
            { "inserted",        "Inserted" },
            { "updated",         "Updated" },
            { "skipped",         "Skipped" },
            { "colKey",          "Key" },
            { "colValue",        "Value" },
            { "colStatus",       "Status" },
            { "statusInserted",  "Inserted" },
            { "statusUpdated",   "Updated" },
            { "statusSkipped",   "Skipped" },
            { "ready",           "Ready" },
            { "loadingSchemas",  "Loading schemas..." },
            { "loadingTables",   "Loading tables..." },
            { "loadingCols",     "Loading columns..." },
            { "previewing",      "Running preview..." },
            { "syncing",         "Syncing..." },
            { "selectSchema",    "-- Select Schema --" },
            { "selectTable",     "-- Select Table --" },
            { "selectKeyCol",    "-- Select Key Column --" },
            { "noFile",          "Please select a JSON file." },
            { "noJson",          "Please paste JSON content." },
            { "noSchema",        "Please select a schema." },
            { "noTable",         "Please select a table." },
            { "noKeyCol",        "Please select a key column." },
            { "invalidJson",     "Invalid JSON" },
            { "upToDate",        "All records are already up to date. Nothing to sync." },
            { "confirmSync",     "Sync {0} record(s) to {1}.{2}?\n\nThis will insert new and update changed records." },
            { "confirmRollback", "Delete {0} inserted record(s) from {1}.{2}?\n\nThis cannot be undone." },
            { "syncDone",        "Sync completed!\n\nInserted: {0}\nSkipped: {1}" },
            { "rollbackDone",    "Rollback successful! {0} record(s) deleted." },
            { "rollbackInfo",    "⚠ {0} record(s) inserted. Click Rollback to undo." },
            { "previewDone",     "Preview done — {0} to insert, {1} to skip." },
            { "connError",       "Connection Error" },
            { "error",           "Error" },
            { "confirm",         "Confirm" },
            { "yes",             "Yes" },
            { "no",              "No" },
            { "savePreset",      "💾 Save Preset" },
            { "loadPreset",      "📁 Load Preset" },
            { "presetSaved",     "Preset saved!" },
            { "language",        "Language" },
        };

        private static readonly Dictionary<string, string> TR = new Dictionary<string, string>
        {
            { "title",           "BelSync" },
            { "schema",          "Şema" },
            { "table",           "Tablo" },
            { "keyCol",          "Anahtar Kolon" },
            { "jsonData",        "JSON Verisi" },
            { "uploadFile",      "📂 Dosya Yükle" },
            { "pasteJson",       "📋 JSON Yapıştır" },
            { "browse",          "Gözat..." },
            { "preview",         "🔍 Önizleme" },
            { "sync",            "💾 Veritabanına Aktar" },
            { "rollback",        "↩ Geri Al" },
            { "clear",           "🗑 Temizle" },
            { "settings",        "⚙ Ayarlar" },
            { "theme",           "🌙 Koyu Mod" },
            { "themeLight",      "☀ Açık Mod" },
            { "total",           "Toplam" },
            { "inserted",        "Eklendi" },
            { "updated",         "Güncellendi" },
            { "skipped",         "Atlandı" },
            { "colKey",          "Anahtar" },
            { "colValue",        "Değer" },
            { "colStatus",       "Durum" },
            { "statusInserted",  "Eklendi" },
            { "statusUpdated",   "Güncellendi" },
            { "statusSkipped",   "Atlandı" },
            { "ready",           "Hazır" },
            { "loadingSchemas",  "Şemalar yükleniyor..." },
            { "loadingTables",   "Tablolar yükleniyor..." },
            { "loadingCols",     "Kolonlar yükleniyor..." },
            { "previewing",      "Önizleme çalışıyor..." },
            { "syncing",         "Aktarılıyor..." },
            { "selectSchema",    "-- Şema Seçin --" },
            { "selectTable",     "-- Tablo Seçin --" },
            { "selectKeyCol",    "-- Anahtar Kolon Seçin --" },
            { "noFile",          "Lütfen bir JSON dosyası seçin." },
            { "noJson",          "Lütfen JSON içeriği yapıştırın." },
            { "noSchema",        "Lütfen bir şema seçin." },
            { "noTable",         "Lütfen bir tablo seçin." },
            { "noKeyCol",        "Lütfen bir anahtar kolon seçin." },
            { "invalidJson",     "Geçersiz JSON" },
            { "upToDate",        "Tüm kayıtlar zaten güncel. Aktarılacak bir şey yok." },
            { "confirmSync",     "{0} kaydı {1}.{2} tablosuna aktarmak istiyor musunuz?\n\nYeni kayıtlar eklenecek ve değişenler güncellenecek." },
            { "confirmRollback", "{0} eklenen kaydı {1}.{2} tablosundan silmek istiyor musunuz?\n\nBu işlem geri alınamaz." },
            { "syncDone",        "Aktarım tamamlandı!\n\nEklendi: {0}\nAtlandı: {1}" },
            { "rollbackDone",    "Geri alma başarılı! {0} kayıt silindi." },
            { "rollbackInfo",    "⚠ {0} kayıt eklendi. Geri almak için Geri Al'a tıklayın." },
            { "previewDone",     "Önizleme tamamlandı — {0} eklenecek, {1} atlanacak." },
            { "connError",       "Bağlantı Hatası" },
            { "error",           "Hata" },
            { "confirm",         "Onay" },
            { "yes",             "Evet" },
            { "no",              "Hayır" },
            { "savePreset",      "💾 Ön Ayar Kaydet" },
            { "loadPreset",      "📁 Ön Ayar Yükle" },
            { "presetSaved",     "Ön ayar kaydedildi!" },
            { "language",        "Dil" },
        };

        private static readonly Dictionary<string, string> AR = new Dictionary<string, string>
        {
            { "title",           "BelSync" },
            { "schema",          "المخطط" },
            { "table",           "الجدول" },
            { "keyCol",          "العمود المفتاح" },
            { "jsonData",        "بيانات JSON" },
            { "uploadFile",      "📂 تحميل ملف" },
            { "pasteJson",       "📋 لصق JSON" },
            { "browse",          "استعراض..." },
            { "preview",         "🔍 معاينة" },
            { "sync",            "💾 مزامنة" },
            { "rollback",        "↩ تراجع" },
            { "clear",           "🗑 مسح" },
            { "settings",        "⚙ الإعدادات" },
            { "theme",           "🌙 الوضع الداكن" },
            { "themeLight",      "☀ الوضع الفاتح" },
            { "total",           "الإجمالي" },
            { "inserted",        "مُدرج" },
            { "updated",         "مُحدَّث" },
            { "skipped",         "متخطى" },
            { "colKey",          "المفتاح" },
            { "colValue",        "القيمة" },
            { "colStatus",       "الحالة" },
            { "statusInserted",  "مُدرج" },
            { "statusUpdated",   "مُحدَّث" },
            { "statusSkipped",   "متخطى" },
            { "ready",           "جاهز" },
            { "loadingSchemas",  "جاري تحميل المخططات..." },
            { "loadingTables",   "جاري تحميل الجداول..." },
            { "loadingCols",     "جاري تحميل الأعمدة..." },
            { "previewing",      "جاري المعاينة..." },
            { "syncing",         "جاري المزامنة..." },
            { "selectSchema",    "-- اختر المخطط --" },
            { "selectTable",     "-- اختر الجدول --" },
            { "selectKeyCol",    "-- اختر العمود المفتاح --" },
            { "noFile",          "الرجاء اختيار ملف JSON." },
            { "noJson",          "الرجاء لصق محتوى JSON." },
            { "noSchema",        "الرجاء اختيار مخطط." },
            { "noTable",         "الرجاء اختيار جدول." },
            { "noKeyCol",        "الرجاء اختيار العمود المفتاح." },
            { "invalidJson",     "JSON غير صالح" },
            { "upToDate",        "جميع السجلات محدثة بالفعل. لا يوجد شيء للمزامنة." },
            { "confirmSync",     "مزامنة {0} سجل إلى {1}.{2}؟\n\nسيتم إدراج سجلات جديدة وتحديث المتغيرة." },
            { "confirmRollback", "حذف {0} سجل مُدرج من {1}.{2}؟\n\nلا يمكن التراجع عن هذا." },
            { "syncDone",        "اكتملت المزامنة!\n\nمُدرج: {0}\nمتخطى: {1}" },
            { "rollbackDone",    "نجح التراجع! تم حذف {0} سجل." },
            { "rollbackInfo",    "⚠ تم إدراج {0} سجل. انقر تراجع للتراجع." },
            { "previewDone",     "اكتملت المعاينة — {0} للإدراج، {1} للتخطي." },
            { "connError",       "خطأ في الاتصال" },
            { "error",           "خطأ" },
            { "confirm",         "تأكيد" },
            { "yes",             "نعم" },
            { "no",              "لا" },
            { "savePreset",      "💾 حفظ الإعداد المسبق" },
            { "loadPreset",      "📁 تحميل الإعداد المسبق" },
            { "presetSaved",     "تم حفظ الإعداد المسبق!" },
            { "language",        "اللغة" },
        };
    }
}